# Generated by Django 2.2.16 on 2022-02-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220207_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'notes of famous people'},
        ),
    ]
