# Generated by Django 2.2.16 on 2022-02-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220207_1831'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_subscription',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_subscription_by_myself',
        ),
    ]
